FROM rust:1.94-bookworm AS build
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY web ./web
RUN cargo build --release --locked

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=build /src/target/release/palmcast /palmcast
EXPOSE 8080
USER nonroot
ENTRYPOINT ["/palmcast"]
CMD ["--port", "8080", "--bind", "0.0.0.0"]
